In [1]:
import numpy as np

In [2]:
n_array = np.arange(1000000)

In [3]:
n_array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [4]:
python_list = list(range(1000000))

In [5]:
#python_list

In [6]:
%time for _ in range(10): [item * 3 for item in python_list]

Wall time: 1.53 s


In [7]:
%time for _ in range(10): n_array = n_array*3

Wall time: 42.9 ms


In [8]:
#BASIC NumPY

In [9]:
arr1 = np.array([1,2,6,4,3,6])

In [10]:
arr1

array([1, 2, 6, 4, 3, 6])

In [16]:
arr2 = np.array([[3,4,2,1,6],[4,7,2,1,6]], dtype = 'float64')

In [17]:
arr2.shape

(2, 5)

In [18]:
arr1.shape

(6,)

In [19]:
type(arr1)

numpy.ndarray

In [20]:
arr2.dtype

dtype('float64')

In [21]:
arr2

array([[3., 4., 2., 1., 6.],
       [4., 7., 2., 1., 6.]])

In [22]:
# Blank Array creation

In [23]:
np.zeros(4)

array([0., 0., 0., 0.])

In [24]:
np.zeros(4, dtype='int32')

array([0, 0, 0, 0])

In [25]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [28]:
np.empty(5) #garbage values

array([8.48798317e-314, 2.12199579e-314, 8.48798317e-314, 4.24399159e-314,
       1.27319747e-313])

In [29]:
#NumPy Arithemetic

In [42]:
array1 = np.array([[1,5,3,2], [3,7,3,9]])

In [43]:
array2 = np.array([[3,5,4,7],[2,8,1,5]])

In [44]:
array1

array([[1, 5, 3, 2],
       [3, 7, 3, 9]])

In [45]:
array2

array([[3, 5, 4, 7],
       [2, 8, 1, 5]])

In [46]:
array1+array2

array([[ 4, 10,  7,  9],
       [ 5, 15,  4, 14]])

In [47]:
array1-array2

array([[-2,  0, -1, -5],
       [ 1, -1,  2,  4]])

In [48]:
array1*array2   #scalar multiplication  #Hadamard Product

array([[ 3, 25, 12, 14],
       [ 6, 56,  3, 45]])

In [49]:
array1**array2

array([[      1,    3125,      81,     128],
       [      9, 5764801,       3,   59049]], dtype=int32)

In [50]:
1/array2

array([[0.33333333, 0.2       , 0.25      , 0.14285714],
       [0.5       , 0.125     , 1.        , 0.2       ]])

In [51]:
#SLICING

In [52]:
arr1 = np.array([2,6,4,2,1,7,5])

In [53]:
#Reference pointer C -- Reflect changes in original array also 

In [54]:
arr = arr1[3:5]

In [56]:
arr

array([2, 1])

In [58]:
arr[0] = 9

In [59]:
arr1

array([2, 6, 4, 9, 1, 7, 5])

In [60]:
#Duplicate copy

In [71]:
arr2 = np.array([3,7,5,6,3,7,8])

In [72]:
arr = arr2[3:5].copy()

In [73]:
arr

array([6, 3])

In [74]:
arr[0] = 15

In [75]:
arr2

array([3, 7, 5, 6, 3, 7, 8])

In [76]:
# Slicing in 2D Array

In [77]:
array1 = np.array([[1,2,3],[4,5,6]])

In [78]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
array1[1,2]

6

In [81]:
#Axis 

In [82]:
ar1 = np.array([[1,2,3],[4,5,6]])

In [85]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
#axis 0 -> Column wise    axis 1 ->Row wise

In [86]:
ar1.sum(axis = 1)

array([ 6, 15])

In [87]:
ar1.sum(axis = 1)

array([ 6, 15])

In [90]:
#dir(np)

In [91]:
len(dir(np))

606

In [92]:
#Dot and Cross product

In [93]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
ar2 = np.array([[7,8,9],[2,8,0]])

In [95]:
ar2

array([[7, 8, 9],
       [2, 8, 0]])

In [98]:
ar1.dot(ar2.transpose())  #matrix multiplication

array([[ 50,  18],
       [122,  48]])

In [100]:
np.dot(ar1,ar2.transpose())  #OR

array([[ 50,  18],
       [122,  48]])

In [101]:
np.cross(ar1,ar2)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [102]:
#SORTING

In [103]:
arr3 = np.array([[4,1,2],[15,3,1]])

In [107]:
arr3

array([[ 4,  1,  2],
       [15,  3,  1]])

In [105]:
np.sort(arr3)  #by default axis = 1

array([[ 1,  2,  4],
       [ 1,  3, 15]])

In [106]:
np.sort(arr3, axis = 0)

array([[ 4,  1,  1],
       [15,  3,  2]])

In [108]:
np.sort(arr3, axis = 1, kind = 'mergesort')

array([[ 1,  2,  4],
       [ 1,  3, 15]])

In [109]:
#argsort, argmin, argmax

In [110]:
a = np.arange(6)

In [111]:
a.ndim

1

In [112]:
b = np.array([4,3,2,1,5,3,1,7,9,4,2,6])

In [116]:
np.argsort(b)

array([ 3,  6,  2, 10,  1,  5,  0,  9,  4, 11,  7,  8], dtype=int64)

In [117]:
np.argmin(b)

3

In [118]:
np.argmax(b)

8

In [119]:
b = b.reshape(4,3)

In [120]:
b

array([[4, 3, 2],
       [1, 5, 3],
       [1, 7, 9],
       [4, 2, 6]])

In [121]:
np.argsort(b)

array([[2, 1, 0],
       [0, 2, 1],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [122]:
np.argsort(b, axis = 0)

array([[1, 3, 0],
       [2, 0, 1],
       [0, 1, 3],
       [3, 2, 2]], dtype=int64)